[package]
name = "movie-derive"
version = "0.1.0"
authors = ["Paweł Zmarzły <pawo2500@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
serde_scan = "0.3.2"
movie = {path = "../movie"}
